# Generated by Django 3.2.4 on 2021-06-28 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_alter_hero_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hero',
            new_name='User',
        ),
    ]
